### ISSUE TITLE
Stakehouse LSD Management - Full Test

### ISSUE THREAD

**Issue by Pol-Lanski** [dappnode/stakehouse-cli#1]
This is a testing review for creating a Dappnode LSD.
All items need to be checked and tested in testnet before releasing an LSD.

Working document.

- [ ] #2
- [ ] #3
- [ ] #4
- [ ] Active Validator: What happens? Where to see info
- [ ] Active Validator: What happens if I set the fee recipient wrong? How do I get penalized?
- [ ] Inactive Validator
- [ ] N.O. wants to stop. What do?
- [ ] Bonus point: From the point of view of the liquidity provider, wat do if I want to get my ETH back?
